[project]
name = "django-datastar-examples"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "datastar-py>=0.8.0",
    "django>=6.0.2",
    "python-decouple>=3.8",
]

[tool.ruff.format]
quote-style = "single"
